# Generated by Django 5.0.4 on 2024-07-05 19:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esuser',
            name='user_type',
        ),
        migrations.AlterField(
            model_name='esuser',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='CPF must be 11 digits.', regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='esuser',
            name='phone',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be 11 digits.', regex='^\\d{11}$')]),
        ),
    ]
