# Generated by Django 5.0.4 on 2024-07-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_esuser_user_type_alter_esuser_cpf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_name', models.CharField(max_length=255)),
                ('street_number', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=20)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('local_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Local',
                'verbose_name_plural': 'Locals',
            },
        ),
    ]
