# Generated by Django 5.0.4 on 2024-07-24 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_local'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='local',
            options={'ordering': ['id'], 'verbose_name': 'Local', 'verbose_name_plural': 'Locals'},
        ),
    ]
