# Generated by Django 5.0.4 on 2024-08-16 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_eventregistration'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationPresence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presence', models.BooleanField()),
                ('type', models.CharField(choices=[('participant', 'Participant'), ('organizer', 'Organizer')], default='participant', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('date_presence', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registration Presence',
                'verbose_name_plural': 'Registration Presences',
                'unique_together': {('user', 'event')},
            },
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
