# Generated by Django 5.0.4 on 2024-08-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_registrationpresence_delete_eventregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationpresence',
            name='presence',
            field=models.BooleanField(default=False),
        ),
    ]
